Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its
application.

Data Scaling is a data preprocessing step for numerical features. Many machine learning algorithms like Gradient descent methods, KNN algorithm, linear and logistic regression, etc. require data scaling to produce good results. Various scalers are defined for this purpose. This article concentrates on Standard Scaler and Min-Max scaler. The task here is to discuss what they mean and how they are implemented using in-built functions that come with this package.

Apart from supporting library functions other functions that will be used to achieve the functionality are:

The fit(data) method is used to compute the mean and std dev for a given feature so that it can be used further for scaling.
The transform(data) method is used to perform scaling using mean and std dev calculated using the .fit() method.
The fit_transform() method does both fit and transform.

In [2]:
from sklearn.preprocessing import StandardScaler
 

data = [[11, 2], [3, 7], [0, 10], [11, 8]]

scaler = StandardScaler()
model = scaler.fit(data)
scaled_data = model.transform(data)
 

print(scaled_data)

[[ 0.97596444 -1.61155897]
 [-0.66776515  0.08481889]
 [-1.28416374  1.10264561]
 [ 0.97596444  0.42409446]]


Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?
Provide an example to illustrate its application.

Scaling is done considering the whole feature vector to be of unit length. This usually means dividing each component by the Euclidean length of the vector (L2 Norm). In some applications (e.g., histogram features), it can be more practical to use the L1 norm of the feature vector.

Like Min-Max Scaling, the Unit Vector technique produces values of range [0,1]. When dealing with features with hard boundaries, this is quite useful. For example, when dealing with image data, the colors can range from only 0 to 255.

In [7]:
import seaborn as sns
from sklearn.preprocessing import normalize

In [8]:
df=sns.load_dataset('iris')

In [11]:
normal=normalize(df[['sepal_width']])

In [12]:
normal

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an
example to illustrate its application.

Principal Component Analysis(PCA) technique was introduced by the mathematician Karl Pearson in 1901. It works on the condition that while the data in a higher dimensional space is mapped to data in a lower dimension space, the variance of the data in the lower dimensional space should be maximum. 
Principal Component Analysis (PCA) is a statistical procedure that uses an orthogonal transformation that converts a set of correlated variables to a set of uncorrelated variables.PCA is the most widely used tool in exploratory data analysis and in machine learning for predictive models. Moreover, 
Principal Component Analysis (PCA) is an unsupervised learning algorithm technique used to examine the interrelations among a set of variables. It is also known as a general factor analysis where regression determines a line of best fit. 
The main goal of Principal Component Analysis (PCA) is to reduce the dimensionality of a dataset while preserving the most important patterns or relationships between the variables without any prior knowledge of the target variables. 
Principal Component Analysis (PCA) is used to reduce the dimensionality of a data set by finding a new set of variables, smaller than the original set of variables, retaining most of the sample’s information, and useful for the regression and classification of data.

In [13]:
from sklearn.decomposition import PCA

In [14]:
df1=df[['sepal_width','sepal_length']]

In [16]:
pca = PCA(n_components=2)

In [17]:
pca.fit(df1)
x_pca = pca.transform(df1)

In [18]:
x_pca

array([[-7.78147798e-01,  3.78132552e-01],
       [-9.35090313e-01, -1.37007280e-01],
       [-1.15130764e+00,  4.53387267e-02],
       [-1.24248065e+00, -6.27699381e-02],
       [-8.86256463e-01,  4.69305555e-01],
       [-5.13096618e-01,  8.02099381e-01],
       [-1.26788414e+00,  2.36152565e-01],
       [-8.69320802e-01,  2.70023887e-01],
       [-1.42482665e+00, -2.78987268e-01],
       [-9.43558144e-01, -3.73664462e-02],
       [-4.96160957e-01,  6.02817712e-01],
       [-1.06860247e+00,  2.53088226e-01],
       [-1.03473115e+00, -1.45475111e-01],
       [-1.53293532e+00, -1.87814264e-01],
       [-1.23001111e-01,  9.35611537e-01],
       [-2.56513268e-01,  1.32570704e+00],
       [-5.13096618e-01,  8.02099381e-01],
       [-7.78147798e-01,  3.78132552e-01],
       [-2.05706284e-01,  7.27862038e-01],
       [-8.03551290e-01,  6.77055055e-01],
       [-4.70757465e-01,  3.03895210e-01],
       [-7.95083459e-01,  5.77414220e-01],
       [-1.28481980e+00,  4.35434233e-01],
       [-7.

Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature
Extraction? Provide an example to illustrate this concept.

Principal component analysis (PCA) is an unsupervised linear transformation technique which is primarily used for feature extraction and dimensionality reduction. It aims to find the directions of maximum variance in high-dimensional data and projects the data onto a new subspace with equal or fewer dimensions than the original one. In the diagram given below, note the directions of maximum variance of data. This is represented using PCA1 (first maximum variance) and PC2 (2nd maximum variance).
How is PCA different than other feature selection techniques?
The way PCA is different from other feature selection techniques such as random forest, regularization techniques, forward/backward selection techniques etc is that it does not require class labels to be present (thus called as unsupervised). More details along with Python code example will be shared in future posts.

In [19]:
from sklearn.decomposition import PCA
df1=df[['sepal_width','sepal_length']]
pca = PCA(n_components=2)
pca.fit(df1)
x_pca = pca.transform(df1)

In [20]:
x_pca

array([[-7.78147798e-01,  3.78132552e-01],
       [-9.35090313e-01, -1.37007280e-01],
       [-1.15130764e+00,  4.53387267e-02],
       [-1.24248065e+00, -6.27699381e-02],
       [-8.86256463e-01,  4.69305555e-01],
       [-5.13096618e-01,  8.02099381e-01],
       [-1.26788414e+00,  2.36152565e-01],
       [-8.69320802e-01,  2.70023887e-01],
       [-1.42482665e+00, -2.78987268e-01],
       [-9.43558144e-01, -3.73664462e-02],
       [-4.96160957e-01,  6.02817712e-01],
       [-1.06860247e+00,  2.53088226e-01],
       [-1.03473115e+00, -1.45475111e-01],
       [-1.53293532e+00, -1.87814264e-01],
       [-1.23001111e-01,  9.35611537e-01],
       [-2.56513268e-01,  1.32570704e+00],
       [-5.13096618e-01,  8.02099381e-01],
       [-7.78147798e-01,  3.78132552e-01],
       [-2.05706284e-01,  7.27862038e-01],
       [-8.03551290e-01,  6.77055055e-01],
       [-4.70757465e-01,  3.03895210e-01],
       [-7.95083459e-01,  5.77414220e-01],
       [-1.28481980e+00,  4.35434233e-01],
       [-7.

Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset
contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to
preprocess the data.

In [21]:
food={
    "price":[20,30,40,50,60],
    "rating":[1,2,3,4,5],
    "delivery":[30,45,32,56,42]
}

In [25]:
import pandas as pd
df1=pd.DataFrame(food)

In [26]:
df1

price  rating  delivery
0     20       1        30
1     30       2        45
2     40       3        32
3     50       4        56
4     60       5        42

In [27]:
from sklearn.preprocessing import MinMaxScaler

In [28]:
min_max=MinMaxScaler()

In [29]:
min_max.fit_transform(df1[["price","rating","delivery"]])

array([[0.        , 0.        , 0.        ],
       [0.25      , 0.25      , 0.57692308],
       [0.5       , 0.5       , 0.07692308],
       [0.75      , 0.75      , 1.        ],
       [1.        , 1.        , 0.46153846]])

Q6. You are working on a project to build a model to predict stock prices. The dataset contains many
features, such as company financial data and market trends. Explain how you would use PCA to reduce the
dimensionality of the dataset.

We can you pca to convert many features into 1d or 2d feature using the pca to reduce the dimensionality of the data.

Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the
values to a range of -1 to 1.

In [49]:
data_sets=[-23, -2, 10, 15, 20]

In [50]:
import numpy as np
np_array=np.array(data_sets)

In [51]:
np_array=np_array.reshape((-1,1))

In [52]:
min_max=MinMaxScaler()

In [53]:
min_max.fit_transform(np_array)

array([[0.        ],
       [0.48837209],
       [0.76744186],
       [0.88372093],
       [1.        ]])

Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform
Feature Extraction using PCA. How many principal components would you choose to retain, and why?

In [56]:
df2={
    "height":[162,167,175,178,182],
    "weight":[56,62,68,72,78],
    "age":[20,23,24,26,30],
    "gender":["male","female","male","female","male"],
    "blood pressure":[66,77,76,84,104]
}


In [57]:
df3=pd.DataFrame(df2)

In [63]:
df4=df3[["height","weight","age","blood pressure"]]

In [64]:
pca = PCA()


In [65]:
pca.fit(df4)
x_pca = pca.transform(df4)

In [66]:
x_pca

array([[-2.22465819e+01, -2.33967723e+00, -1.19647111e-01,
         3.44922091e-02],
       [-8.46356627e+00, -3.30687548e+00,  1.76451931e-01,
        -3.85395569e-02],
       [-2.93112772e+00,  5.13746519e+00, -1.15493565e-01,
        -4.00367893e-02],
       [ 6.62352557e+00,  3.86058380e+00,  1.51635618e-01,
         4.25245630e-02],
       [ 2.70177503e+01, -3.35149628e+00, -9.29468735e-02,
         1.55957419e-03]])