Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
sklearn.datasets.

In [111]:
import pandas as pd
import numpy as np
from  sklearn.datasets import load_iris

In [112]:
dataset=load_iris()

In [113]:
df=pd.DataFrame(data=dataset.data,columns=dataset.feature_names)

In [114]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [115]:
X=df
y=dataset.target

In [116]:
X,y

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 array([0, 0, 0, 0, 0, 0,

In [117]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.33)

In [118]:
from sklearn.neighbors import KNeighborsClassifier

In [119]:
classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')

In [120]:
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [121]:
y_pred=classifier.predict(X_test)

In [122]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [123]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in
sklearn.datasets.

In [15]:
##boston dataset is no longer available in sklearn

from sklearn.datasets import load_boston

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [59]:
##boston data has been removed from the sklearn so use the california housing data set
from sklearn.datasets import fetch_california_housing

In [60]:
dataset=fetch_california_housing()

In [61]:
df=pd.DataFrame(data=dataset.data,columns=dataset.feature_names)

In [62]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [63]:
X=df
y=dataset.target

In [64]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.33)


In [65]:
from sklearn.neighbors import KNeighborsRegressor

In [66]:
regressor=KNeighborsRegressor(n_neighbors=5,algorithm='auto')

In [67]:
regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [68]:
y_pred=regressor.predict(X_test)

In [69]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [70]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.129955281414476
0.8297297099236641
1.1594144708644052


Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
cross-validation on load_iris dataset in sklearn.datasets.

In [42]:
param_grid={
    'n_neighbors':[5,10,15]
}

In [43]:
from sklearn.model_selection import GridSearchCV

In [44]:
grid=GridSearchCV(classifier,param_grid=param_grid)

In [45]:
grid.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [5, 10, 15]})

In [46]:
grid.best_params_

{'n_neighbors': 5}

In [47]:
y_pred=grid.predict(X_test)

In [48]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
sklearn.datasets.

In [71]:
from sklearn.preprocessing import StandardScaler

In [72]:
scaler=StandardScaler()

In [73]:
X_train_scaled=scaler.fit_transform(X_train)

In [74]:
X_test_scaled=scaler.transform(X_test)

In [75]:
regressor.fit(X_train_scaled,y_train)

KNeighborsRegressor()

In [76]:
y_pred=regressor.predict(X_test_scaled)

In [77]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.6696691374123126
0.4502669004697592
0.44019620379965413


Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
load_iris dataset in sklearn.datasets.

In [94]:
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC

In [96]:
svc=SVC()

In [100]:
voting=VotingClassifier(estimators=[('KNN',classifier),('svc',svc)],voting='hard')

In [101]:
voting.fit(X_train,y_train)

VotingClassifier(estimators=[('KNN', KNeighborsClassifier()), ('svc', SVC())])

In [102]:
y_pred=voting.predict(X_test)

In [103]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



Q6. Implement a function to standardise the features before applying KNN classifier.

In [124]:
def Standardise(X_train,X_test):
    std=StandardScaler()
    train_scaled=std.fit_transform(X_train)
    test_scaled=std.transform(X_test)
    return train_scaled,test_scaled

In [125]:
X_train,X_test=Standardise(X_train,X_test)

In [126]:
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [129]:
y_pred=classifier.predict(X_test)

In [130]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



Q7. Write a Python function to calculate the euclidean distance between two points.

In [131]:
def euclidean_distance(p1, p2):
  """
  Calculates the Euclidean distance between two points.

  Args:
    p1: The first point.
    p2: The second point.

  Returns:
    The Euclidean distance between the two points.
  """

  assert len(p1) == len(p2)

  distance = 0
  for i in range(len(p1)):
    distance += (p1[i] - p2[i]) ** 2

  return distance ** 0.5

In [132]:
euclidean_distance((1,2),(3,4))

2.8284271247461903

Q8. Write a Python function to calculate the manhattan distance between two points.

In [133]:
def manhattan_distance(p1, p2):
  """
  Calculates the Manhattan distance between two points.

  Args:
    p1: The first point.
    p2: The second point.

  Returns:
    The Manhattan distance between the two points.
  """

  return sum(abs(p1[i] - p2[i]) for i in range(len(p1)))

In [134]:
manhattan_distance((1,2),(3,4))

4