Q1. What is the relationship between polynomial functions and kernel functions in machine learning
algorithms?

In machine learning, the polynomial kernel is a kernel function commonly used with support vector machines (SVMs) and other kernelized models, that represents the similarity of vectors (training samples) in a feature space over polynomials of the original variables, allowing learning of non-linear models.

Q2. How can we implement an SVM with a polynomial kernel in Python using Scikit-learn?

While creating SVM we should specific the kernal paramter as poly.
EX:-
SVM(kernal='ploy')

Q3. How does increasing the value of epsilon affect the number of support vectors in SVR?

A larger value of epsilon will result in a less stringent model that will be less sensitive to individual outliers or errors, but this could lead to underfitting. In Support Vector Machines (SVMs), epsilon is a parameter used in epsilon-insensitive regression.

Q4. How does the choice of kernel function, C parameter, epsilon parameter, and gamma parameter
affect the performance of Support Vector Regression (SVR)? Can you explain how each parameter works
and provide examples of when you might want to increase or decrease its value?

In [1]:
from  sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [2]:
dataset=load_iris()

In [3]:
df=pd.DataFrame(data=dataset.data,columns=dataset.feature_names)

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
X=df
y=dataset.target

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.33)

In [7]:
X_test.shape,y_test.shape

((50, 4), (50,))

In [9]:
from sklearn.svm import SVR

In [10]:
svc=SVR(kernel='linear',C=1,gamma=0.1,epsilon=0.2)

In [11]:
svc.fit(X_train,y_train)

SVR(C=1, epsilon=0.2, gamma=0.1, kernel='linear')

In [12]:
y_pred=svc.predict(X_test)

In [15]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.9345082782345574


In [16]:
##now after chaning the gamma,kernel and epsilon
svc=SVR(kernel='rbf',C=2,gamma=0.2,epsilon=0.3)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)

In [17]:
print(r2_score(y_test,y_pred))

0.9241990873844508


In [ ]:
#As you can see from  above difference between the r2 score because of changing parameters

Q5. Assignment:
1.Import the necessary libraries and load the dataseg
2.Split the dataset into training and testing setZ
3.Preprocess the data using any technique of your choice (e.g. scaling, normaliMationK
4.Create an instance of the SVC classifier and train it on the training datW
5.hse the trained classifier to predict the labels of the testing datW
6.Evaluate the performance of the classifier using any metric of your choice (e.g. accuracy,
precision, recall, F1-scoreK
7.Tune the hyperparameters of the SVC classifier using GridSearchCV or RandomiMedSearchCV to
improve its performanc_
8.Train the tuned classifier on the entire dataseg
9.Save the trained classifier to a file for future use.

In [18]:
from  sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [19]:
dataset=load_iris()

In [20]:
df=pd.DataFrame(data=dataset.data,columns=dataset.feature_names)

In [22]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [23]:
##dependent and independent features
X=df
y=dataset.target

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.33)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
standard=StandardScaler()

In [27]:
X_train=standard.fit_transform(X_train)
X_test=standard.transform(X_test)

In [28]:
from sklearn.svm import SVC

In [29]:
svc=SVC(kernel='linear')

In [30]:
svc.fit(X_train,y_train)

SVC(kernel='linear')

In [31]:
y_pred=svc.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_pred,y_pred))

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]
0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



In [33]:
from sklearn.model_selection import GridSearchCV
param_gird={'kernel':['linear','poly', 'rbf','sigmoid'],
            'C':[1,2,3,0.1,4,5],
            'gamma':['scale','auto']
           }

In [34]:
grid=GridSearchCV(svc,param_grid=param_gird,cv=5,scoring='accuracy')

In [35]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(kernel='linear'),
             param_grid={'C': [1, 2, 3, 0.1, 4, 5], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='accuracy')

In [36]:
grid.best_params_

{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}

In [37]:
y_pred=grid.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_pred,y_pred))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        15

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

